services:
  pytorch:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/workspace
    command: 'jupyter-lab'
    ports:
      - 8888:8888
    ipc: host
